import { Edge } from "@xyflow/react";

// Worker Lifecycle Management
export default [
  {
    id: "e1",
    source: "lifespan",
    target: "run_livekit_worker",
    animated: true,
  },
  {
    id: "e3",
    source: "run_livekit_worker",
    target: "run_forever",
    animated: true,
  },
  {
    id: "e2",
    source: "run_forever",
    target: "run_worker_async",
    animated: true,
  },
  {
    id: "e5",
    source: "lifespan",
    target: "start_worker",
    animated: true,
    label: "X number of workers",
  },
  {
    id: "e16",
    source: "start_worker",
    target: "register_with_dial_manager",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e17",
    source: "run_worker_async",
    target: "worker_options",
    type: "smoothstep",
    animated: true,
  },

  {
    id: "e18",
    source: "LiveKitAPI_list_dispatch",
    target: "entrypoint",
    animated: true,
  },

  // Call Setup and Configuration
  {
    id: "e13",
    source: "app_config",
    target: "set_thread_id",
    animated: true,
  },
  {
    id: "e14",
    source: "app_config",
    target: "get_thread_id",
    animated: true,
  },
  {
    id: "e40",
    source: "set_call_metadata",
    target: "set_call_metadata_passthrough",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e42332",
    source: "set_call_metadata_passthrough",
    target: "set_call_metadata_app_config",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e30",
    source: "start_outbound_call",
    target: "call_config",
    animated: true,
  },
  {
    source: "call_config",
    target: "LiveKitAPI",
    id: "53ubg0jzo9h",
    animated: true,
  },

  // Dialing Flow
  {
    id: "e19",
    source: "start_worker",
    target: "super_run",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e16adfsd",
    source: "super_run",
    target: "run_dialer",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e21",
    source: "run_dialer",
    target: "set_up_environment",
    animated: true,
  },
  {
    id: "e22",
    source: "set_up_environment",
    target: "business_hours_check",
    animated: true,
  },
  {
    id: "e23",
    source: "business_hours_check",
    target: "get_next_customer",
    animated: true,
  },
  {
    id: "e20",
    source: "get_next_customer",
    target: "set_call_metadata",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e24",
    source: "set_call_metadata",
    target: "handle_outbound_call_livekit",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e25",
    source: "handle_outbound_call_livekit",
    target: "get_or_create_outbound_trunk",
    animated: true,
  },
  {
    id: "e25aasdfa",
    source: "get_or_create_outbound_trunk",
    target: "LiveKitOutboundCall_creation",
    animated: true,
  },
  {
    source: "LiveKitOutboundCall_creation",
    target: "start_outbound_call",
    type: "smoothstep",
    id: "wzok3nrscjq",
    animated: true,
  },
  {
    source: "shutdown_hook_call",
    target: "coalesce_livekit_messages",
    id: "wzok3nrasjfsscjq",
    animated: true,
    type: "smoothstep",
  },

  // Call Status and Router Management
  {
    id: "e6",
    source: "calls_router",
    target: "get_router",
    animated: true,
  },
  {
    id: "e7",
    source: "calls_router",
    target: "handle_call_status",
    animated: true,
  },
  {
    id: "e10",
    source: "livekit_call_status_manager",
    target: "manage_call",
    animated: true,
  },
  {
    id: "e11",
    source: "manage_call",
    target: "handle_call_status_manager",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e12",
    source: "manage_call",
    target: "cleanup",
    animated: true,
    type: "smoothstep",
  },
  {
    source: "manage_call",
    target: "update_call_state",
    animated: true,
    id: "xy-edge__manage_call-update_call_state",
    type: "smoothstep",
  },
  {
    source: "update_call_state",
    target: "sleep_state",
    animated: true,
    id: "xy-edge__update_call_state-sleep_state",
  },

  // Call Pipeline and Processing
  {
    source: "setup_call_metadata",
    target: "get_post_call_processor",
    animated: true,
    id: "xy-edge__setup_call_metadata-get_post_call_processor",
  },
  {
    source: "get_post_call_processor",
    target: "get_call_metadata",
    animated: true,
    id: "xy-edge__get_post_call_processor-get_call_metadata",
  },
  {
    source: "get_call_metadata",
    target: "create_sip_participant",
    animated: true,
    id: "xy-edge__get_call_metadata-create_sip_participant",
  },
  {
    source: "create_sip_participant",
    target: "run_voice_pipeline_agent_call",
    animated: true,
    type: "smoothstep",
    id: "xy-edge__create_sip_participant-run_voice_pipeline_agent_call",
  },
  {
    source: "run_voice_pipeline_agent_call",
    target: "graph_manager",
    animated: true,
    id: "xy-edge__run_voice_pipeline_agent_call-graph_manager",
  },

  // LangGraph Integration
  {
    source: "graph_manager",
    target: "langgraph_agent",
    animated: true,
    id: "xy-edge__graph_manager-langgraph_agent",
  },
  {
    source: "langgraph_agent",
    target: "langgraph_llm",
    animated: true,
    id: "xy-edge__langgraph_agent-langgraph_llm",
  },
  {
    source: "langgraph_llm",
    target: "agent_instance",
    animated: true,
    id: "xy-edge__langgraph_llm-agent_instance",
  },
  {
    source: "agent_instance",
    target: "langgraph_agent_instance_start",
    animated: true,
    id: "xy-edge__agent_instance-run_voice_pipeline_agent_call",
  },
  {
    source: "langgraph_agent_instance_start",
    target: "run_voice_pipeline_agent_call",
    animated: true,
    id: "xy-edge__langgraph_agent_instance_start-run_voice_pipeline_agent_call",
    label: "return agent instance",
  },
  {
    source: "run_voice_pipeline_agent_call",
    target: "LiveKitCallStatusManager",
    animated: true,
    id: "xy-run_voice_pipeline_agent_call-LiveKitCallStatusManager",
    label: "pass agent instance",
  },
  {
    source: "run_voice_pipeline_agent_call",
    target: "initialize_pipeline",
    animated: true,
    id: "xy-run_voice_pipeline_agent_call-initialize_pipeline",
  },

  // Shutdown and Cleanup
  {
    id: "e34",
    source: "coalesce_livekit_messages",
    target: "print_history",
    animated: true,
  },
  {
    id: "aksl;fkja-asdhf;a`",
    source: "print_history",
    target: "post_call_processor_call",
    animated: true,
  },
  {
    source: "LiveKitCallStatusManager",
    target: "LiveKitCallStatusManager_manage",
    animated: true,
    id: "xy-edge__LiveKitCallStatusManager-LiveKitCallStatusManager_manage",
  },
  {
    source: "LiveKitCallStatusManager_manage",
    target: "manage_call",
    animated: true,
    id: "xy-LiveKitCallStatusManager_manage-manage_call",
    type: "smoothstep",
  },
  {
    source: "post_call_processor_call",
    target: "process_call",
    id: "m7zwhe22bz",
    animated: true,
    type: "smoothstep",
  },
  {
    source: "process_call",
    target: "get_call_result",
    id: "62o1xzkzbmw",
    animated: true,
  },
  {
    source: "get_call_result",
    target: "save_call_to_salient",
    id: "rjpq2j7u0df",
    animated: true,
  },
  {
    source: "save_call_to_salient",
    target: "save_call_to_customer",
    id: "q40zjgjhouf",
    animated: true,
  },
  {
    source: "save_call_to_customer",
    target: "clean_up",
    id: "38fe3hgqkui",
    animated: true,
  },

  // Make Dials
  {
    source: "make-dials",
    target: "reinitialize_app_config",
    id: "xy-edge__make-dials-reinitialize_app_config",
    animated: true,
    type: "smoothstep",
  },
  {
    source: "reinitialize_app_config",
    target: "start_worker",
    id: "xy-edge__reinitialize_app_config-start_worker",
    animated: true,
    type: "smoothstep",
  },

  // Voice Pipeline to Graph Manager Flow
  {
    source: "initialize_pipeline",
    target: "graph_manager_init",
    targetHandle: "graph_manager_init-top",
    id: "xy-initialize_pipeline-graph_manager_init",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "graph_manager_init",
    sourceHandle: "graph_manager_init-left",
    target: "reinitialize_graph",
    id: "xy-graph_manager_init-reinitialize_graph",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "reinitialize_graph",
    target: "graph_manager_init",
    targetHandle: "graph_manager_init-right",
    id: "xy-reinitialize_graph-graph_manager_init",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "graph_manager_init",
    target: "langgraph_config",
    sourceHandle: "graph_manager_init-bottom",
    id: "xy-graph_manager_init-langgraph_config",
    type: "smoothstep",
  },
  {
    source: "reinitialize_graph",
    target: "initialize_memory",
    id: "xy-reinitialize_graph-initialize_memory",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "initialize_memory",
    target: "configure_langgraph",
    id: "xy-initialize_memory-configure_langgraph",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "configure_langgraph",
    target: "get_client_config",
    id: "xy-configure_langgraph-langgraph_config",
    type: "smoothstep",
    animated: true,
  },

  // Voice Pipeline to Langgraph Flow
  {
    source: "graph_manager_init",
    target: "langgraph_config",
    targetHandle: "langgraph_config-top",
    id: "xy-initialize_pipeline-langgraph_config",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "langgraph_config",
    target: "langgraph_agent",
    sourceHandle: "langgraph_config-left",
    id: "xy-langgraph_config-langgraph_agent",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "langgraph_agent",
    target: "langgraph_config",
    targetHandle: "langgraph_config-right",
    id: "xy-langgraph_agent-langgraph_config",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "langgraph_config",
    target: "voice_pipeline_agent",
    targetHandle: "voice_pipeline_agent-top",
    id: "xy-langgraph_config-voice_pipeline_agent",
    type: "smoothstep",
    animated: true,
  },

  // Voice Pipeline Agent to Agent Instance Flow
  {
    source: "voice_pipeline_agent",
    target: "agent_instance",
    sourceHandle: "voice_pipeline_agent-left",
    id: "xy-voice_pipeline_agent-agent_instance",
    type: "smoothstep",
    animated: true,
  },
  {
    source: "agent_instance",
    target: "voice_pipeline_agent",
    targetHandle: "voice_pipeline_agent-right",
    id: "xy-agent_instance-voice_pipeline_agent",
    animated: true,
    type: "smoothstep",
  },
  {
    source: "voice_pipeline_agent",
    target: "run_voice_pipeline_agent_call",
    sourceHandle: "voice_pipeline_agent-bottom",
    id: "xy-voice_pipeline_agent-run_voice_pipeline_agent_call",
    type: "smoothstep",
    animated: true,
  },
] as Edge[];
